
spring:
  cloud:
    loadbalancer:
      configurations: health-check
      eager-load:
        clients: feb-case-proc,feb-catalogs,feb-enquery-proc,feb-alerts-proc
      health-check:
        refetch-instances-interval: 30s
        refetch-instances: true
        path:
          default: /veradat-actuator/health


logging:
  level:
    root: WARN
    com.veradat: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
  pattern:
    console: '%d %-5level [%thread] [%logger ]: %msg%n'

management:
  endpoint:
    logfile:
      enabled: true
    health:
      show-components: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile
      base-path: /veradat-actuator
  health:
    defaults:
      enabled: false
    rabbit:
      enabled: false
    redis:
      enabled: true


jwt:
  secret: $Pasdwew45sdf
   
veradat:
  microserviceId: FCO
  rest:
    client: webclient
    validate-certs: true
    keystore:
    keystorePassword: notifierqa
    tlsVersion: TLSv1.2
    check_after_inactivity_ms: 1000
    times_to_retry_on_error: 3
    time_to_retry_on_status_error_ms: 3000
    maxRateLimit: 30
    initialRateLimit: 15
    timeout: 50000
    responseTime_ms: 10000
    conn_timeout: 15000
    request_max_avg: 10
    request_max_pending_on_queue: 100
    request_pending_on_queue_timeout_ms: 10000
    crt: /etc/crt
    key: /etc/key

  restClients:
    - name: GET-CASES
      controller: feb-case-proc
      path: /api/v1/case/search
      method: POST
      external: false

    - name: GET-CASES-SINGLE-ROW
      controller: feb-case-proc
      path: /api/v1/case/search/single-row
      method: POST
      external: false

    - name: GET-CASE-DETAIL
      controller: feb-case-proc
      path: /api/v1/case/detail
      method: POST
      external: false

    - name: VALIDATE-CATALOG
      controller: feb-catalogs
      path: /api/v1/catalogs/validate/{catalogType}/{businessKey}
      method: GET
      external: false

    - name: GET-CASE
      controller: feb-case-proc
      path: /api/v1/case
      method: POST
      external: false

    - name: GET-ENQUERY-CONVERSATION-INFO
      controller: feb-enquery-proc
      path: /api/v1/enquery/conversation-info
      method: POST
      external: false

    - name: GET-ALERT-CONVERSATION-INFO
      controller: feb-alerts-proc
      path: /api/v1/alerts/conversation-info
      method: POST
      external: false

  broker-messages:
    global:
      reprocessQueue: vdt_general_reprocess_queue
      dlqQueue: vdt_general_dlq_queue
      securityEventQueue: vdt_security_event_queue
    rabbitmq:
      general:
        reprocessRoutingKey: vdt.general_reprocess_queue.routingkey
        reprocessExchange: veradat.general.exchange
        dlqRoutingKey: vdt.general_dlq_queue.routingkey
        dlqExchange: veradat.general.exchange
        securityEventRoutingKey: vdt.security_event.routingkey
        securityExchange: veradat.security.exchange
      output:
        queues:
          - name: UPDATE-CASE-STATUS
            queue: feb.transversal_update-case-status.queue
            exchange: feb.transversal.exchange
            routingKey: feb.transversal_update-case-status.routing_key

          - name: UPDATE-CASE-USER
            queue: feb.transversal_update-case-user.queue
            exchange: feb.transversal.exchange
            routingKey: feb.transversal_update-case-user.routing_key

          - name: CLOSE-CONVERSATION
            queue: feb.message_close-conversations.queue
            exchange: feb.message.exchange
            routingKey: feb.message_close-conversations.routing_key
      reply:
        timeout: 60000
        maxAttempts: 3
        interval: 3000
      concurrent:
        consumers: 1
      max:
        concurrent:
          consumers: 2
      missingQueuesFatal: false
      recoveryInitialInterval: 30000
      recoveryMultiplierInterval: 2
      recoveryMaxInterval: 120000
      heartbeat: 60
      networkRecoveryInterval: 60
      channelCacheSize: 25
      ssl:
        enabled: false
        keyStoreType: jks
        trustStoreType: jks
        skipServerCertificateValidation: false
        sslAlgorithm: TLSv1.2
