### Configuracion que no debe ir en el configuration service
jwt:
  secret: $Pasdwew45sdf

spring:  
  data:
    redis:
      repositories:
        enabled: false
  cloud:
    loadbalancer:
      configurations: health-check
      eager-load:
        clients: feb-enquery-proc,feb-cfg-proc,feb-watchlist-proc,veradat-feb-node-security-grant-proc,feb-catalogs
      health-check:
        refetch-instances-interval: 30s
        refetch-instances: true
        path:
          default: /veradat-actuator/health


logging:
  level:
    root: WARN
    com.veradat: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
  pattern:
    console: '%d %-5level [%thread] [%logger ]: %msg%n'

management:
  endpoint:
    logfile:
      enabled: true
    health:
      show-components: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile
      base-path: /veradat-actuator
  health:
    defaults:
      enabled: false
    rabbit:
      enabled: false
    redis:
      enabled: true

veradat:
  microserviceId: FEO
  #nodeId: 40-012
  resources:
    redis:
      database: 0
      defaultExpirationTime: 30
      lockTime: 10000
      tryLockTime: 20000
  
  rest:
    #Generales
    client: webclient
    validate-certs: true
    keystore:
    keystorePassword: notifierqa
    tlsVersion: TLSv1.2
    check_after_inactivity_ms: 9000 #timeout para obtener la conexion con el servidor
    times_to_retry_on_error: 3
    time_to_retry_on_status_error_ms: 3000
    maxRateLimit: 30
    initialRateLimit: 15
    timeout: 50000 #timeout para las respuesta del server
    responseTime_ms: 10000 # especifica el tiempo promedio en que se espera la respuesta del servidor
    conn_timeout: 15000
    request_max_avg: 10
    request_max_pending_on_queue: 100
    request_pending_on_queue_timeout_ms: 10000
    #Especificos para webClient
    crt: /etc/crt
    key: /etc/key

  errors:
    internal-error: Ocurrio un error interno, pior favor consulte con el administrador de sistema
  security:
    permissions:
      disabled: false
  broker-messages:    
    global:
      reprocessQueue: vdt_general_reprocess_queue
      dlqQueue: vdt_general_dlq_queue
      securityEventQueue: vdt_security_event_queue
    rabbitmq:
      general:
        reprocessRoutingKey: vdt.general_reprocess_queue.routingkey
        reprocessExchange: veradat.general.exchange
        dlqRoutingKey: vdt.general_dlq_queue.routingkey
        dlqExchange: veradat.general.exchange
        securityEventRoutingKey: vdt.security_event.routingkey
        securityExchange: veradat.security.exchange
      routingkey: rabbitmq.routingkey
      reply:
        timeout: 60000
        maxAttempts: 3
        interval: 3000
      concurrent:
        consumers: 1
      max:
        concurrent:
          consumers: 2
      output:
        queues:
          - name: create-folio
            queue: feb.enquery_create-enquery-folio.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_create-enquery-folio.routing_key
          - name: notify-enquery
            queue: feb.enquery_notify-enquery.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_notify-enquery.routing_key
          - name: notify-enquery-batch
            queue: feb.enquery_notify-enquery-batch.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_notify-enquery-batch.routing_key
          - name: create-enquery
            queue: feb.enquery_create-enquery.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_create-enquery.routing_key
          - name: create-enquery-batch
            queue: feb.enquery_create-enquery-batch.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_create-enquery-batch.routing_key
          - name: update-enquery-details
            queue: feb.enquery_update-enquery-details.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_update-enquery-details.routing_key
          - name: update-enquery-details-batch
            queue: feb.enquery_update-enquery-details-batch.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_update-enquery-details-batch.routing_key
          - name: batch-processed
            queue: feb.batch_national-processed.queue
            exchange: feb.batch.exchange
            routingKey: feb.batch_national-processed.routing_key
          - name: requeue-local-enquery
            queue: feb.enquery_requeue-local-enquery.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_requeue-local-enquery.routing_key
          - name: requeue-local-enquery-batch
            queue: feb.enquery_requeue-local-enquery-batch.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_requeue-local-enquery-batch.routing_key
          - name: update-enquery
            queue: feb.enquery_update-enquery.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_update-enquery.routing_key
          - name: update-enquery-batch
            queue: feb.enquery_update-enquery-batch.queue
            exchange: feb.enquery.exchange
            routingKey: feb.enquery_update-enquery-batch.routing_key

      input:
        queues:
          folio:
            name: feb.enquery_return-enquery-folio.queue
            enabled: true
          batch:
            name: feb.batch_process-national-enquery.queue
            enabled: true
          requeue-local-enquery:
            name: feb.enquery_requeue-local-enquery.queue
            enabled: true
          requeue-local-enquery-batch:
            name: feb.enquery_requeue-local-enquery-batch.queue
            enabled: true
          create-enquery-ack:
            name: feb.enquery_create-enquery-ack.queue
            enabled: true
          create-enquery-ack-batch:
            name: feb.enquery_create-enquery-ack-batch.queue
            enabled: true

      missingQueuesFatal: false
      recoveryInitialInterval: 30000
      recoveryMultiplierInterval: 2
      recoveryMaxInterval: 120000
      heartbeat: 60
      networkRecoveryInterval: 60
      channelCacheSize: 25
      ssl:
        keyStoreType: jks
        trustStoreType: jks
        skipServerCertificateValidation: false
        sslAlgorithm: TLSv1.2
  restclients:
    - name: VALIDATE-PERSON-TYPE
      controller: feb-catalogs
      path: /api/v1/catalogs/personTypes/validate/{businessKey}
      method: GET
      external: false

    - name: VALIDATE-COUNTRY
      controller: feb-catalogs
      path: /api/v1/catalogs/countries/validate/{businessKey}
      method: GET
      external: false

    - name: VALIDATE-GENDER
      controller: feb-catalogs
      path: /api/v1/catalogs/genders/validate/{businessKey}
      method: GET
      external: false

    - name: VALIDATE-POSTAL-CODE
      controller: feb-catalogs
      path: /api/v1/catalogs/postalCodes/validate/{country}/{code}
      method: GET
      external: false

    - name: VALIDATE-BANK
      controller: feb-catalogs
      path: /api/v1/catalogs/institutions/validate/BNK/{code}
      method: GET
      external: false

    - name: GET-ENQUERY-RESULTS
      controller: feb-enquery-proc
      path: /api/v1/watchlist/enquery/{folio}
      method: GET
      external: false

    - name: VALIDATE-GENERATION-AREA
      controller: feb-catalogs
      path: /api/v1/catalogs/validate/case_generated_by/{businessKey}
      method: GET
      external: false

    - name: GET-ENQUERY-HIST
      controller: feb-enquery-proc
      path: /api/v1/enquery/history/search
      method: POST
      external: false

    - name: GET-HITS-HIST
      controller: feb-enquery-proc
      path:     /api/v1/enquery/hits/detail
      method: POST
      external: false

    - name: ENQUERY-NATIONAL
      controller: feb-watchlist-proc
      path: /api/v1/watchlist/national
      method: POST
      external: false

    - name: ENQUERY-FOREIGN
      controller: feb-watchlist-proc
      path: /api/v1/watchlist/foreign
      method: POST
      external: false

    - name: ENQUERY-ESCROW
      controller: feb-watchlist-proc
      path: /api/v1/watchlist/escrow
      method: POST
      external: false

    - name: VALIDATE-AREA
      controller: veradat-feb-node-security-grant-proc
      path: /api/v1/areas/businessKey
      method: POST
      external: false

    - name: GET-NODE-CFG
      controller: feb-cfg-proc
      path: /api/v1/cfg/node
      method: GET
      external: false
